name: docker-django-example #Project-Name
services:
  web:
    image: ${IMAGE_NAME}:${WEB_TAG}
    build: . 
    container_name: ${APP_NAME}-app
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    ports:
      - ${WEB_PORT}:8000
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy       
    logging:
        driver: "json-file"
        options:
            max-file: 10
            max-size: 50m     
    networks:
      - app-network 
      
  db:
    image: postgres:16.2-alpine3.19
    container_name: ${APP_NAME}-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - ${DB_PORT}:5432
    env_file:
      - ./.env.db
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}'"]
      interval: 10s
      timeout: 3s
      retries: 3     
    networks:
      - app-network  
volumes:
  postgres_data:
  cache:
networks:
  app-network:
    name: ${APP_NAME}
